platform :ios, '8.0'
workspace '../XNGOAuth1Client'

target 'XNGOAuth1ClientExample' do
  pod 'XNGOAuth1Client', :path => '../XNGOAuth1Client.podspec'

  target 'XNGOAuth1ClientTests' do
    inherit! :search_paths
    pod 'Expecta',     '~> 0.2.3'
    pod 'OHHTTPStubs', '~> 3.1.0'
  end
end

begin
  require 'slather'
rescue LoadError
  puts 'Slather has been disabled (not installed).'
end
