platform :ios, '6.1'
workspace '../XNGOAuth1Client'

pod 'XNGOAuth1Client', :path => '../XNGOAuth1Client.podspec'

target 'XNGOAuth1ClientTests', :exclusive => true do
  pod 'Expecta',     '~> 0.2.3'
  pod 'OHHTTPStubs', '~> 3.1.0'
end
