platform :ios, '8.0'
workspace '../XNGOAuth1Client'

pod 'XNGOAuth1Client', :path => '../XNGOAuth1Client.podspec'

target 'XNGOAuth1ClientTests' do
  pod 'Expecta',     '~> 0.2.3'
  pod 'OHHTTPStubs', '~> 3.1.0'
end

begin
  require 'slather'
rescue LoadError
  puts 'Slather has been disabled (not installed).'
end
